<?php

function simplewiki_library() {
  return array(
    'simplewiki' => array(
      'title' => 'SimpleWiki', 
      'website' => 'http://simplewiki.org/',
      'js' => array(
        drupal_get_path('module', 'simplewiki') . '/SimpleWiki.js' => array(),
      ), 
      'css' => array(
        drupal_get_path('module', 'simplewiki') . '/SimpleWiki.css' => array(
          'type' => 'file', 
          'media' => 'screen',
        ),
      ),
    ),
  );
}

function simplewiki_help($path = 'admin/help#simplewiki', $arg) {
  switch ($path) {
    case 'admin/help#simplewiki':
      return t('<p>The SimpleWiki filter allows you to enter content using <a href="http://simplewiki.org/language">SimpleWiki</a>, a simple plain-text syntax that is transformed into valid HTML.</p>');
      break;
  }
}

function simplewiki_filter_info() {
  $filters['filter_simplewiki'] = array(
    'title' => t('SimpleWiki'),
    'description' => t('Allows content to be submitted using SimpleWiki, a simple plain-text syntax that is filtered into valid HTML.'),
    'process callback' => '_filter_simplewiki',
    'settings callback' => '_filter_simplewiki_settings',
    'tips callback'  => '_filter_simplewiki_tips'
  );
  return $filters;
}

function _filter_simplewiki_settings($form, &$form_state, $filter, $format, $defaults) {
  $filter->settings += $defaults;
  $elements = array();
  $elements['autotoc'] = array(
    '#type' => 'checkbox', 
    '#title' => t('Automatically generate Table of Contents'), 
    '#default_value' => isset($filter->settings['autotoc']) ? $filter->settings['autotoc'] : 0,
  );
  return $elements;
}

function _filter_simplewiki_tips($format, $long = FALSE) {
  if ($long) {
    return t('<p>SimpleWiki markup starts with the creole markup set for basic markup, then adds decorators (both inline decorators and block decorators) and block declarations for advanced markup.</p><p>!image</p><p>See the <a href="@simplewiki">SimpleWiki language page</a> for full details.', array('!image' => theme('image', array('path'=>drupal_get_path('module', 'simplewiki') .'/creole_cheat_sheet.png')), '@simplewiki' => 'http://simplewiki.org/language'));
  }
  else {
    return t('You can use <a href="@filter_tips">SimpleWiki syntax</a> to format and style the text.', array('@filter_tips' => url('filter/tips')));
  }
}

function _filter_simplewiki($text, $format) {
  if (!empty($text)) {
    include_once drupal_get_path('module', 'simplewiki') .'/SimpleWiki.php';
	  $wiki = new SimpleWiki($text);
	  if ($format->settings['autotoc']) {
  	  $wiki->register_events(array('onemit' => array($wiki,'auto_quicktoc')));
	  }
	  $text = $wiki->get_html();
  }
  return $text;
}

